name: IOTHunt
main: uk.co.staticvoid.iothunt.IOTHunt
version: 0.5
api-version: 1.13
author: MajorSlackmore
commands:
   push-button:
      description: Pushes a button on the IoT Hunt leaderboard
      usage: /push-button <button-number>
      